name: Deployment

on:
  push:
    branches:
      - main

concurrency:
  group: deployment
  cancel-in-progress: false
  queue: max

jobs:
  staging-deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout
        uses: actions/checkout@v5.1.0

      - name: Configure node
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Sync to S3 staging bucket
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ./dist
          destination: s3://${{ vars.AWS_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}

  prodution-deployment:
    runs-on: ubuntu-latest
    environment: production
    needs: staging-deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v5.1.0

      - name: Configure node
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: .nvmrc

      - name: Install packages
        run: npm ci

      - name: Build
        run: npm run build

      - name: Sync to S3 production bucket
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: sync
          source: ./dist
          destination: s3://${{ vars.AWS_BUCKET_NAME }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ vars.AWS_REGION }}
